default: &default
  adapter: postgresql
  pool: 5
  encoding: utf8
  timeout: 5000

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: moissenger
