# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe5e6899d86e1845c4984691b615b5bf280fea50c3db83c0b938039fbb373a2bb3e1736aab5538d1936ba075a4d198ecdf7537cf7fc7d5357265ef8efcb5083

test:
  secret_key_base: 4fc3761e736b27ab3fdc3f561506441f63258470ecc391fc1376a85f1cf78f3644f000d318553cc58379d861e7e2dced0a1b26dd73e05706557346574528ab62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
